global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['192.168.1.23:9101']
        labels:
          node_name: 'AGX03'
      - targets: ['192.168.1.15:9101']
        labels:
          node_name: 'NANO05'

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          cnode_name: 'AGX03-Docker'
      - targets: ['192.168.1.16:8090']
        labels:
          cnode_name: 'Nano06-Docker'
      - targets: ['192.168.1.15:8090']
        labels:
          cnode_name: 'Nano06-Docker'

  - job_name: 'tegrastats_exporter'
    static_configs:
      - targets: ['192.168.1.23:8085']
        labels:
          tnode_name: 'AGX03'
      - targets: ['192.168.1.15:8085']
        labels:
          tnode_name: 'Nano05'
      - targets: ['192.168.1.16:8085']
        labels:
          tnode_name: 'Nano06'
