version: '2.3'

services:

  fl-client:
    image: openfl-client-1:latest
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
#    command: nvidia-smi
    container_name: openfl-client-1
#    command: --ip=192.168.1.50 --folder=ba
    networks:
      - federated-net

networks:
  federated-net:
    driver: bridge